# Measurement of aquifer properties

From very local measurements to regional parameter assessments

## Flow meter test
This section presents the data available for evaluationg a flowmeter experiment. The raw data can be downloaded from [github](https://github.com/mabesa/Documentation_GW_field_course_2020/tree/master/_bookdown_files/data/Experiments_aquifer_properties/).   

Data set 1 was measured in borehole 6.1. The groundwater table was at 3.75m below the rim of the borehole. The screened section of the borehole is between 9.5m and 14.5m below the rim. The diameter of the borehole is 10.5cm.    
The flowmeter was moved at a constant speed of 7m/s for the experiments labeled contl in Figure \@ref(fig:flow-meter-data-set1). In a second experiment, point measurements were taken at intervals of 50cm (labeled point in Figure \@ref(fig:flow-meter-data-set1)).   
```{r flow-meter-data-set1, echo=FALSE, out.width='100%', fig.cap='Data set 1 of the flow meter test in borehole 6.1. cont and point indicate continuous lowering & rising of the flow meter and point measurements at defined depths respectively under non-pumping conditions. '}
fl1 <- read.csv('_bookdown_files/data/Experiments_aquifer_properties/flowmeter1.csv',
                sep=';', row.names = NULL,
                col.names=c('ID','Time_ms','Depth_cm','FlowUP_Hz','FlowDN_Hz','N'))
fl1 %>%
  mutate(Flow=FlowUP_Hz-FlowDN_Hz) %>% 
  filter(ID!='test', ID!='windingspeed', ID!='wspeed2') %>%
  ggplot() + 
  geom_point(aes(Flow,Depth_cm/100,color=Time_ms), size=0.2) + 
  facet_wrap('ID') + 
  scale_y_continuous(trans = "reverse") + 
  geom_hline(yintercept=3.75,color='blue') +
  geom_hline(yintercept=9.5,color='gray') + 
  geom_hline(yintercept=14.5,color='gray') + 
  labs(x='Flow (>0:Up, <0:Down) [Hz]', y='Depth [m]', 
       title='Data set 1, borehole 6.1', color='Time [ms]') + 
  theme_bw()
```

#### Task 10: Evaluate flow meter test
Follow the steps in [@Molz1989] to determine flow velocities and hydaulic conductivities along the borehole. 

## Dilution test

## Slug test

## Pumping test

## Tracer test
